# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-15 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballers',
            name='player_img',
            field=models.CharField(blank=True, db_column='Image_URL', max_length=200, null=True),
        ),
    ]
